// Generated by CoffeeScript 1.9.3
var setupIcons, setupTitle, spinAndFill;

$(function() {
  var height, s, stuck, width;
  width = $("#logo-wrapper").width();
  height = $("#logo-wrapper").height();
  stuck = false;
  s = skrollr.init({
    constants: {
      music: height,
      bio: 2 * height
    },
    forceHeight: false
  });
  $(window).scroll(function() {
    if (s.getScrollTop() > height) {
      stuck = true;
      return $('#nav').css({
        position: "fixed",
        top: "0px",
        bottom: "80%"
      });
    } else if (stuck) {
      return $("#nav").css({
        position: "absolute",
        top: "80%",
        bottom: "0%"
      });
    }
  });
  $("#music-btn").click(function() {
    return s.animateTo(height, {
      duration: 500
    });
  });
  return $("#bio-btn").click(function() {
    return s.animateTo(2 * height, {
      duration: 500
    });
  });
});

setupTitle = function() {
  var image, logoPattern, paper;
  paper = Snap("#logo");
  image = paper.image("imgs/logo-background.jpg", 0, 0, 1200, 400).attr({
    opacity: 0
  });
  logoPattern = image.pattern(0, 0, 1200, 400);
  paper.append(logoPattern);
  return Snap.load("imgs/logo-c.svg", function(f) {
    var bbox, logo;
    logo = f.select('#logo');
    paper.append(logo);
    bbox = logo.getBBox();
    logo.attr({
      fill: "none",
      stroke: "#fff",
      "stroke-width": 2,
      "stroke-dasharray": "150 75"
    });
    logo.animate({
      "stroke-dasharray": "1200 400"
    }, 3000);
    return setTimeout(function() {
      var $btns;
      return $btns = $('.nav-btn').removeClass('hidden', 2000);
    });
  });
};

spinAndFill = function(el, filler) {
  var bbox, cx, cy;
  el.attr({
    fill: filler
  });
  if (el.inAnim().length === 0) {
    bbox = el.getBBox();
    cx = bbox.cx;
    cy = bbox.cy;
    el.transform("r0," + cx + "," + cy);
    return el.animate({
      transform: "r360," + cx + "," + cy
    }, 1000, mina.bounce);
  }
};

setupIcons = function() {
  var fb, soundcloud, spotify;
  soundcloud = Snap("#soundcloud-icon");
  Snap.load("imgs/soundcloud-icon.svg", function(f) {
    var icon;
    icon = f.select('#icon');
    soundcloud.append(icon);
    return $('.icon-wrapper:has(#soundcloud-icon)').hover((function() {
      return spinAndFill(icon, "r()#ff7024-#FF5510");
    }), function() {
      return icon.attr({
        fill: "#000"
      });
    });
  });
  spotify = Snap("#spotify-icon");
  Snap.load("imgs/spotify-icon.svg", function(f) {
    var icon;
    icon = f.select('#icon');
    spotify.append(icon);
    return $('.icon-wrapper:has(#spotify-icon)').hover((function() {
      return spinAndFill(icon, "r()#95f205-#7DC211");
    }), function() {
      return icon.attr({
        fill: "#000"
      });
    });
  });
  fb = Snap('#fb-icon');
  return Snap.load("imgs/facebook-icon.svg", function(f) {
    var icon;
    icon = f.select('#icon');
    fb.append(icon);
    return $('.icon-wrapper:has(#fb-icon)').hover((function() {
      return spinAndFill(icon, "#3C5A99");
    }), function() {
      return icon.attr({
        fill: "#000"
      });
    });
  });
};

$(function() {
  setupTitle();
  return setupIcons();
});
